---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-secret
  labels:
    app: {{ .Values.appname }}
    app.kubernetes.io/name: "{{ .Values.appname }}"
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}
